### ISSUE TITLE
Limit to github origin

### ISSUE THREAD

**Issue by blois** [googlecolab/open_in_colab#1]
Should be able to limit the extension to only github URLs with:
https://developer.chrome.com/apps/match_patterns

**Comment by jakevdp** [comment]
I think it's useful for something to happen when the extension is clicked on a non-github page, otherwise users might think it just doesn't work.

**Comment by jakevdp** [comment]
Looking into this; if I'm understanding the chrome docs correctly, it looks like match patterns only apply to content scripts, which run with access to the content of the page. This extension uses a background script, so matching patterns do not apply.

**Comment by peap** [comment]
Idea: display a popup indicating what's supported when the extension icon is clicked in a non-supported context: https://developer.chrome.com/docs/extensions/reference/api/action#method-openPopup

**Comment by peap** [comment]
Resolved by version 1.2.0, which was just submitted for publication.
