### ISSUE TITLE
Colab notebook gets stuck in the loading page

### ISSUE THREAD

**Issue by byom26** [googlecolab/open_in_colab#10]
![image](https://user-images.githubusercontent.com/42446258/133836679-3c4b50c1-6b14-4e79-93e2-4a5303f5c3c8.png)

It gets stuck at the loading page forever. I tried clearing browser cache, incognito mode, deleting colab folder from the drive but nothing works. Facing the issue from last two days

**Comment by peap** [comment]
For general issues with Colab, please use https://github.com/googlecolab/colabtools/issues.
