### ISSUE TITLE
Publish Firefox addon

### ISSUE THREAD

**Issue by domoritz** [googlecolab/open_in_colab#2]
Since this is a webextension, the same code should work as a Firefox add-on.

**Comment by electron0zero** [comment]
I forked and fixed some firefox related warnings and published it: https://addons.mozilla.org/en-US/firefox/addon/open-in-colab/

Source: https://github.com/electron0zero/open_in_colab

**Comment by domoritz** [comment]
Do you want to send a PR to merge the changes into here? I think it would make sense to set browser as `const browser = window.browser || window.chrome;` and maybe have a separate manifest file for firefox. I have a script in https://github.com/domoritz/himawari-8-chrome to build bundles for Firefox and Chrome from the same repo.

**Comment by electron0zero** [comment]
I was going to open a PR but CONTRIBUTING.md says that PR will not be merged.

>  However, we don't have the bandwidth to support review of external contributions, and we don't want user PRs to languish, so we aren't accepting any external contributions right now.
https://github.com/googlecolab/open_in_colab/blob/master/CONTRIBUTING.md#contributing

That's why I forked and published it to Firefox Add-ons.

If you any improvements, please [send PR](https://github.com/electron0zero/open_in_colab), I will be more then happy to merge and publish.

**Comment by domoritz** [comment]
😞 @jakevdp @craigcitro Can you make an exception for this small extension? I doubt that you will get many PRs for this small extension.

**Comment by electron0zero** [comment]
@domoritz more then happy to make a PR if it get's merged :+1:

**Comment by colaboratory-team** [comment]
Hello - thanks for your interest in this! As noted in the above link, we're not able to accept any external contributions in this repo. We were planning to guage interest in this extension, and publish addons for other browsers if there was sufficient interest. It seems you beat us to it!
