### ISSUE TITLE
Add link on store page to github

### ISSUE THREAD

**Issue by domoritz** [googlecolab/open_in_colab#3]
It would be nice to link to the source code from the web store page. Something like this:

<img width="282" alt="screen shot 2018-11-05 at 11 26 11" src="https://user-images.githubusercontent.com/589034/48021535-b4cced00-e0ed-11e8-80de-c8120f9716b6.png">

**Comment by peap** [comment]
Resolved by version 1.2.0, which was just submitted for publication.
