### ISSUE TITLE
A code that ran perfectly well the first time, now provides different errors for different runs without any change in input files

### ISSUE THREAD

**Issue by souvikmeister** [googlecolab/open_in_colab#8]
Hi Everyone,
Here's the training algorithm I am trying to implement:
https://colab.research.google.com/drive/1rgDy-5sPEAk3juqyoWaDBJEu0BSl-AhG?usp=sharing
The respective training, test, and validation files are here:
https://drive.google.com/drive/folders/120p3hzk4NlIodqPKyuVlweRYtZlGxk_A?usp=sharing, https://drive.google.com/drive/folders/1jmjS0UtPrhzOnIAUCk_iExEXFwm4lRx-?usp=sharing, and
https://drive.google.com/file/d/1Np0g6LM3ZcNR4tJ_aDuti8EnkPI_77L-/view?usp=sharing.
It trained well for a smaller size data set.
For this data set it started training upto 71 epochs and then stopped after complaining about buffering issues. 
I am only loading a small batch size of 50 rows at a time in the code from the numpy array stored in the gmail colab folder. So shouldnt have this issue.
Any suggestions would be greatly appreciated. Many thanks.
Souvik

**Comment by peap** [comment]
For general issues with Colab, please use https://github.com/googlecolab/colabtools/issues.
